const state = { library:null, current:null, selectedAdventure:null, selectedUID:'about', editorAdventure:null };
const $ = id => document.getElementById(id);
function backend(){ return window.go?.wailsapp?.App || demoBackend; }

const demoAdventure = { schema_version:'1.0', id:'the-sunken-crypt', title:'The Sunken Crypt', author:'Demo', system:'D&D 5e', language:'en', summary:'A compact crypt adventure demo.', context:'For level 1 characters.', background:'A drowned saint still whispers below.', introduction:'The stairs descend under black water.', conclusion:'The relic can be recovered or lost.', hooks:['A bell rings under the marsh.'], zones:[{id:'upper-crypt', name:'Upper Crypt', overview:'Wet stones and old vows.', rooms:[{id:'entry', name:'Entry Hall', read_aloud:'Cold air rolls down the stair.', dm_notes:'The floor is slick.', npc_ids:['warden'], event_ids:['bell'], exits:[{to:'altar', direction:'east'}]},{id:'altar', name:'Drowned Altar', read_aloud:'Black water pools around a cracked altar.', dm_notes:'A hidden reliquary waits here.'}]}], npcs:[{id:'warden', name:'Crypt Warden', role:'guardian', appearance:'A moss-cloaked skeleton with blue witchlight eyes.', personality:'Formal, tired and suspicious.', motivations:'Keep the oath sealed.', default_location:'entry'}], events:[{id:'bell', name:'The Bell Rings', trigger:'The party crosses the threshold.', description:'A submerged bell tolls once.', read_aloud:'A single bell-note rolls through the crypt.'}], items:[{id:'relic', name:'Saint Oria’s Relic', rarity:'rare', description:'A silver fingerbone case.'}], tables:[{id:'omens', name:'Crypt Omens', dice:'d6', rows:[{roll:'1-3', cells:['A candle gutters.']},{roll:'4-6', cells:['Water ripples against gravity.']}]}] };
function demoTree(adv=demoAdventure){ return [{uid:'about',label:'Adventure',kind:'about'},{uid:'zones',label:'Zones',kind:'section',children:adv.zones.map(z=>({uid:`zone:${z.id}`,label:'▸ '+z.name,kind:'zone',children:z.rooms.map(r=>({uid:`room:${z.id}::${r.id}`,label:(r.id==='entry'?'● Party':'·')+'  '+r.name,kind:'room'}))}))},{uid:'npcs',label:'NPCs',kind:'section',children:adv.npcs.map(n=>({uid:`npc:${n.id}`,label:n.name,kind:'npc'}))},{uid:'events',label:'Events',kind:'section',children:adv.events.map(e=>({uid:`event:${e.id}`,label:e.name,kind:'event'}))},{uid:'items',label:'Items',kind:'section',children:adv.items.map(i=>({uid:`item:${i.id}`,label:i.name,kind:'item'}))},{uid:'tables',label:'Random tables',kind:'section',children:adv.tables.map(t=>({uid:`table:${t.id}`,label:t.name,kind:'table'}))}]; }
const demoBackend = { async GetLibrary(){ return {adventures:[{id:demoAdventure.id,title:demoAdventure.title,author:'Demo',system:'D&D 5e'}],sessions:[{name:'demo-session',adventure_title:demoAdventure.title,current_room:'entry'}],config:{provider:'claude-cli',model:'sonnet',language:'en',auto_save:true,configured:true,config_path:'demo',data_path:'demo'}}}, async GetAdventure(){return demoAdventure}, async NewAdventureTemplate(){return JSON.parse(JSON.stringify(demoAdventure))}, async SaveAdventure(a){demoAdventure.title=a.title;return a}, async StartSession(){return demoSession('room:upper-crypt::entry')}, async LoadSession(){return demoSession('room:upper-crypt::entry')}, async GetDetail(uid){return demoDetail(uid)}, async MoveParty(id){return demoSession(`room:upper-crypt::${id}`)}, async Submit(input){return {success:true,message: input.startsWith('/')?'Command executed.':'Oracle prompt recorded.',session:demoSession('room:upper-crypt::entry')}}, async SaveSession(){return {success:true,message:'Session saved.',session:demoSession('room:upper-crypt::entry')}}, async MarkNPCMet(id){let s=demoSession('npc:'+id);return s}, async TriggerEvent(id){return demoSession('event:'+id)}, async RollTable(){return {success:true,message:'🎲 Crypt Omens — rolled 4: Water ripples against gravity.',session:demoSession('table:omens')}}, async DeleteAdventure(){return this.GetLibrary()}, async DeleteSession(){return this.GetLibrary()}, async RenameSession(){return this.GetLibrary()}, async ImportAdventure(){return {message:'Imported demo',library:await this.GetLibrary()}}, async SaveConfig(c){return c}, async GetConfig(){return (await this.GetLibrary()).config}, async ExportDMBook(path,pdf){return {success:true,message:'DM book exported: '+path,session:demoSession('room:upper-crypt::entry')}}, async ExportNovel(path,pdf){return {success:true,message:'Novel exported: '+path,session:demoSession('room:upper-crypt::entry')}} };
function demoSession(uid){ return {state:{name:'demo-session',adventure_id:demoAdventure.id,adventure_title:demoAdventure.title,current_zone:'upper-crypt',current_room: uid.includes('altar')?'altar':'entry',visited_rooms:{entry:true},log:{entries:[]}}, adventure:demoAdventure, current_room:demoAdventure.zones[0].rooms.find(r=>r.id===(uid.includes('altar')?'altar':'entry')), current_zone:demoAdventure.zones[0], tree:demoTree(), detail:demoDetail(uid)} }
function demoDetail(uid){ const adv=demoAdventure; let md=`## ${adv.title}\n\n**Summary**\n\n${adv.summary}`; let actions=[]; let groups=[]; if(uid?.startsWith('room:')){ const rid=uid.split('::')[1]; const r=adv.zones[0].rooms.find(x=>x.id===rid); md=`## ${r.name}\n\n\` ${r.id} \`\n\n**Read-aloud**\n\n> ${r.read_aloud}\n\n**DM notes**\n\n${r.dm_notes}`; actions=['move']; groups=[{title:'Exits',refs:[{label:'east → Drowned Altar',uid:'room:upper-crypt::altar'}]},{title:'NPCs here',refs:[{label:'Crypt Warden',uid:'npc:warden'}]}]; } if(uid==='npc:warden') md='## Crypt Warden — guardian\n\n**Appearance**\n\nA moss-cloaked skeleton with blue witchlight eyes.\n\n**Personality**\n\nFormal, tired and suspicious.'; return {uid,kind:(uid||'about').split(':')[0],title:'Detail',markdown:md,groups,actions}; }

async function init(){ bindEvents(); await loadLibrary(); if(new URLSearchParams(location.search).get('demo')==='session') await startSelectedAdventure(); }
function bindEvents(){ $('library-btn').onclick=showLibrary; $('settings-btn').onclick=openSettings; $('start-btn').onclick=startSelectedAdventure; $('new-adventure-btn').onclick=newAdventure; $('import-btn').onclick=importAdventure; $('editor-back').onclick=showLibrary; $('editor-save').onclick=saveEditor; $('editor-play').onclick=playEditor; $('editor-validate').onclick=validateEditor; $('send-btn').onclick=submitComposer; $('save-session-btn').onclick=saveSession; $('settings-save').onclick=saveSettings; $('dice-btn').onclick=openDice; $('dice-roll').onclick=rollDice; $('mode-btn').onclick=toggleMode; $('export-dmbook-btn').onclick=()=>openExport('dmbook'); $('export-novel-btn').onclick=()=>openExport('novel'); $('export-run').onclick=runExport; $('search').addEventListener('input',()=>renderSession()); document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addEntity(b.dataset.add)); $('composer').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submitComposer();}}); }
async function loadLibrary(){ state.library=await backend().GetLibrary(); if(!state.selectedAdventure && state.library.adventures?.length) state.selectedAdventure=state.library.adventures[0].id; renderLibrary(); }
function show(view){ ['library-view','editor-view','session-view'].forEach(id=>$(id).classList.toggle('hidden', id!==view)); ['save-session-btn','dice-btn','mode-btn','export-dmbook-btn','export-novel-btn'].forEach(id=>$(id).classList.toggle('hidden', view!=='session-view')); $('start-btn').classList.toggle('hidden', view!=='library-view'); }
function showLibrary(){ show('library-view'); $('crumb').textContent='Library'; loadLibrary(); }
function renderLibrary(){ const advBox=$('adventure-list'); const sessBox=$('session-list'); advBox.innerHTML=''; sessBox.innerHTML=''; (state.library.adventures||[]).forEach(a=>{ const el=div('lib-card'); el.innerHTML=`<h3>${esc(a.title||a.id)}</h3><p>${esc(a.system||'')} ${a.author?`· ${esc(a.author)}`:''}</p><div class="card-actions"><button class="btn primary" data-play="${escAttr(a.id)}">▶ Play</button><button class="btn" data-edit="${escAttr(a.id)}">Edit</button><button class="btn ghost" data-deladv="${escAttr(a.id)}">Delete</button></div>`; advBox.append(el); }); (state.library.sessions||[]).forEach(s=>{ const el=div('lib-card'); el.innerHTML=`<h3>${esc(s.name)}</h3><p>${esc(s.adventure_title||s.adventure_id||'')} ${s.current_room?`· ${esc(s.current_room)}`:''}</p><div class="card-actions"><button class="btn primary" data-load="${escAttr(s.name)}">↻ Resume</button><button class="btn" data-renamesess="${escAttr(s.name)}">Rename</button><button class="btn ghost" data-delsess="${escAttr(s.name)}">Delete</button></div>`; sessBox.append(el); }); advBox.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>startAdventure(b.dataset.play)); advBox.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editAdventure(b.dataset.edit)); advBox.querySelectorAll('[data-deladv]').forEach(b=>b.onclick=()=>deleteAdventure(b.dataset.deladv)); sessBox.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>loadSession(b.dataset.load)); sessBox.querySelectorAll('[data-renamesess]').forEach(b=>b.onclick=()=>renameSession(b.dataset.renamesess)); sessBox.querySelectorAll('[data-delsess]').forEach(b=>b.onclick=()=>deleteSession(b.dataset.delsess)); }
async function startSelectedAdventure(){ const id=state.selectedAdventure || state.library?.adventures?.[0]?.id; if(id) await startAdventure(id); }
async function startAdventure(id){ state.current=await backend().StartSession(id); showSession(); renderSession(); addMsg('system',`Running ${state.current.adventure.title}.`); }
async function loadSession(name){ state.current=await backend().LoadSession(name); showSession(); renderSession(); addMsg('system',`Resumed ${name}.`); }
function showSession(){ show('session-view'); $('crumb').textContent=`Session / ${state.current?.adventure?.title||''}`; updateModeButton(); }
function renderSession(){ if(!state.current)return; renderTree($('adventure-tree'), filterTree(state.current.tree||[], $('search')?.value||'')); renderDetail(state.current.detail); renderTimeline(); $('oracle-subtitle').textContent=state.current.state?.name||'Ask questions and run commands'; updateModeButton(); }
function renderTree(host,nodes){ host.innerHTML=''; const walk=(arr,depth=0)=>arr.forEach(n=>{ const e=div(`node ${n.kind||''} ${state.selectedUID===n.uid?'selected':''}`); e.style.paddingLeft=(8+depth*16)+'px'; e.textContent=n.label; e.onclick=()=>selectNode(n.uid); host.append(e); if(n.children) walk(n.children,depth+1); }); walk(nodes); }
async function selectNode(uid){ state.selectedUID=uid; const detail=await backend().GetDetail(uid); state.current.detail=detail; renderTree($('adventure-tree'), state.current.tree||[]); renderDetail(detail); }
function renderDetail(d){ if(!d)return; $('detail-subtitle').textContent=d.kind||''; $('detail').innerHTML=markdownLite(d.markdown||'') + renderImages(d.images||[]); const actions=$('detail-actions'); actions.innerHTML=''; (d.actions||[]).forEach(a=>{ const b=document.createElement('button'); b.className='btn'; b.textContent=a==='move'?'Move party here':a==='mark_npc_met'?'Mark as met':a==='trigger_event'?'Mark triggered':a==='roll_table'?'Roll on table':a; b.onclick=()=>runDetailAction(a,d.uid); actions.append(b); }); const links=$('detail-links'); links.innerHTML=''; (d.groups||[]).forEach(g=>{ if(!g.refs?.length)return; const h=document.createElement('h4'); h.textContent=g.title; links.append(h); g.refs.forEach(r=>{ const l=div('link'); l.textContent='› '+r.label; l.onclick=()=>selectNode(r.uid); links.append(l); }); }); }
async function runDetailAction(action,uid){ let res; if(action==='move') res=await backend().MoveParty(uid.split('::').pop()); else if(action==='mark_npc_met') res=await backend().MarkNPCMet(uid.replace('npc:','')); else if(action==='trigger_event') res=await backend().TriggerEvent(uid.replace('event:','')); else if(action==='roll_table'){ const out=await backend().RollTable(uid.replace('table:','')); addMsg('system',out.message); res=out.session; } if(res){ state.current=res; renderSession(); } }
function addMsg(role,text){ const el=div('msg '+role); el.textContent=text; $('transcript').append(el); $('transcript').scrollTop=$('transcript').scrollHeight; }
async function submitComposer(){ const raw=$('composer').value.trim(); if(!raw)return; $('composer').value=''; addMsg('user',raw); const res=await backend().Submit(raw); addMsg(res.success?'system':'error',res.message||''); if(res.session){state.current=res.session;renderSession();} }
async function saveSession(){ const res=await backend().SaveSession(); addMsg('system',res.message); }
function openDice(){ $('dice-dialog').showModal(); }
async function rollDice(e){ e.preventDefault(); const notation=$('dice-notation').value.trim()||'1d20'; $('dice-dialog').close(); $('composer').value='/roll '+notation; await submitComposer(); }
async function toggleMode(){ $('composer').value='/mode'; await submitComposer(); }
function updateModeButton(){ const mode=state.current?.state?.mode || state.current?.state?.Mode || ''; $('mode-btn').textContent = String(mode).toLowerCase().includes('virtual') ? 'Mode: Virtual DM' : 'Mode: Oracle'; }
let exportKind='dmbook';
function openExport(kind){ exportKind=kind; const adv=state.current?.adventure?.id||'adventure'; $('export-title').textContent=kind==='novel'?'Export novel':'Export DM book'; $('export-path').value=`/tmp/${adv}-${kind}.md`; $('export-pdf').checked=false; $('export-dialog').showModal(); }
async function runExport(e){ e.preventDefault(); const path=$('export-path').value.trim(); const pdf=$('export-pdf').checked; $('export-dialog').close(); const res= exportKind==='novel' ? await backend().ExportNovel(path,pdf) : await backend().ExportDMBook(path,pdf); addMsg(res.success?'system':'error',res.message); if(res.session){state.current=res.session;renderSession();} }
function renderTimeline(){ const log=state.current.state?.log?.entries || []; $('timeline').innerHTML=log.length?log.slice(-8).map(e=>`<div>${esc(e.type||'note')}: ${esc(e.text||e.room_name||'')}</div>`).join(''):'<div>No timeline entries yet.</div>'; }
async function newAdventure(){ state.editorAdventure=await backend().NewAdventureTemplate(); openEditor(); }
async function editAdventure(id){ state.editorAdventure=await backend().GetAdventure(id); openEditor(); }
function openEditor(){ show('editor-view'); $('crumb').textContent=`Editor / ${state.editorAdventure.title||state.editorAdventure.id}`; $('editor-json').value=JSON.stringify(state.editorAdventure,null,2); renderEditorTree(); }
function renderEditorTree(){ $('editor-tree').innerHTML=''; const a=state.editorAdventure; const rows=[['meta','Adventure']]; (a.zones||[]).forEach(z=>{ rows.push(['zone:'+z.id,'▸ '+z.name]); (z.rooms||[]).forEach(r=>rows.push(['room:'+z.id+'::'+r.id,'·  '+r.name])); }); (a.npcs||[]).forEach(n=>rows.push(['npc:'+n.id,n.name])); (a.events||[]).forEach(e=>rows.push(['event:'+e.id,e.name])); (a.items||[]).forEach(i=>rows.push(['item:'+i.id,i.name])); (a.tables||[]).forEach(t=>rows.push(['table:'+t.id,t.name])); rows.forEach(([uid,label])=>{ const n=div('node'); n.textContent=label; n.onclick=()=>{ $('editor-status').textContent=`Selected ${uid}. Edit JSON directly, then Save.`; }; $('editor-tree').append(n); }); }
function parseEditor(){ state.editorAdventure=JSON.parse($('editor-json').value); return state.editorAdventure; }
async function saveEditor(){ try{ const saved=await backend().SaveAdventure(parseEditor()); state.editorAdventure=saved; $('editor-status').textContent='Saved and installed in library.'; $('editor-json').value=JSON.stringify(saved,null,2); renderEditorTree(); await loadLibrary(); }catch(e){ $('editor-status').textContent='⚠ '+(e.message||e); } }
async function playEditor(){ await saveEditor(); if(state.editorAdventure?.id) await startAdventure(state.editorAdventure.id); }
function validateEditor(){ try{ parseEditor(); $('editor-status').textContent='JSON is valid. Save will run adventure validation.'; renderEditorTree(); }catch(e){ $('editor-status').textContent='⚠ '+e.message; } }
function addEntity(kind){ const a=parseEditor(); const id=kind+'-'+Date.now().toString(36); if(kind==='zone') (a.zones ||= []).push({id,name:'New Zone',rooms:[]}); if(kind==='room') { (a.zones ||= [{id:'zone-1',name:'Starting Zone',rooms:[]}]); (a.zones[0].rooms ||= []).push({id,name:'New Room',read_aloud:'',dm_notes:''}); } if(kind==='npc') (a.npcs ||= []).push({id,name:'New NPC',role:''}); if(kind==='event') (a.events ||= []).push({id,name:'New Event',description:''}); if(kind==='item') (a.items ||= []).push({id,name:'New Item',description:''}); if(kind==='table') (a.tables ||= []).push({id,name:'New Table',dice:'d6',rows:[]}); $('editor-json').value=JSON.stringify(a,null,2); renderEditorTree(); }
async function importAdventure(){ const path=$('import-path').value.trim(); if(!path){ alert('Pega la ruta local del .tar.gz en el campo de importación.'); return; } const res=await backend().ImportAdventure(path); state.library=res.library; renderLibrary(); }
async function deleteAdventure(id){ if(confirm('Delete adventure '+id+'?')){ state.library=await backend().DeleteAdventure(id); renderLibrary(); } }
async function deleteSession(name){ if(confirm('Delete session '+name+'?')){ state.library=await backend().DeleteSession(name); renderLibrary(); } }
async function renameSession(name){ const n=prompt('New session name',name); if(n&&n!==name){ state.library=await backend().RenameSession(name,n); renderLibrary(); } }
async function openSettings(){ const c=await backend().GetConfig(); $('cfg-provider').value=c.provider||''; $('cfg-model').value=c.model||''; $('cfg-run-model').value=c.run_model||''; $('cfg-edit-model').value=c.edit_model||''; $('cfg-language').value=c.language||''; $('cfg-import-language').value=c.import_language||''; $('cfg-temperature').value=c.temperature||0; $('cfg-max-tokens').value=c.max_tokens||0; $('cfg-import-tokens').value=c.import_max_output_tokens||0; $('cfg-tool-iter').value=c.oracle_max_tool_iterations||0; $('cfg-timeout').value=c.request_timeout_seconds||0; $('cfg-autosave-interval').value=c.auto_save_interval||0; $('cfg-autosave').checked=!!c.auto_save; $('cfg-tts-enabled').checked=!!c.tts_enabled; $('cfg-tts-voice').value=c.tts_voice||''; $('cfg-tts-model').value=c.tts_model||''; $('cfg-tts-speed').value=c.tts_speed||1; $('cfg-chat-id').value=c.telegram_chat_id||0; $('settings-meta').textContent=`Config: ${c.config_path||''} · Provider ${c.configured?'ready':'not configured'}`; $('settings-dialog').showModal(); }
async function saveSettings(e){ e.preventDefault(); await backend().SaveConfig({provider:$('cfg-provider').value,model:$('cfg-model').value,run_model:$('cfg-run-model').value,edit_model:$('cfg-edit-model').value,language:$('cfg-language').value,import_language:$('cfg-import-language').value,temperature:Number($('cfg-temperature').value||0),max_tokens:Number($('cfg-max-tokens').value||0),import_max_output_tokens:Number($('cfg-import-tokens').value||0),oracle_max_tool_iterations:Number($('cfg-tool-iter').value||0),request_timeout_seconds:Number($('cfg-timeout').value||0),auto_save:$('cfg-autosave').checked,auto_save_interval:Number($('cfg-autosave-interval').value||0),tts_enabled:$('cfg-tts-enabled').checked,tts_voice:$('cfg-tts-voice').value,tts_model:$('cfg-tts-model').value,tts_speed:Number($('cfg-tts-speed').value||0),telegram_chat_id:Number($('cfg-chat-id').value||0)}); $('settings-dialog').close(); await loadLibrary(); }
function markdownLite(md){ return esc(md).replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/^&gt; (.*)$/gm,'<blockquote>$1</blockquote>').replace(/\n/g,'<br>'); }
function renderImages(images){ return images.length ? '<div class="image-strip">'+images.map(src=>`<img src="${escAttr(src)}" alt="Adventure art">`).join('')+'</div>' : ''; }
function filterTree(nodes,q){ q=String(q||'').trim().toLowerCase(); if(!q)return nodes; const keep=n=>{ const kids=(n.children||[]).map(keep).filter(Boolean); if(String(n.label||'').toLowerCase().includes(q)||kids.length) return {...n,children:kids}; return null; }; return nodes.map(keep).filter(Boolean); }
function div(cls){ const e=document.createElement('div'); e.className=cls; return e; }
function esc(v){ return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); }
function escAttr(v){ return esc(v).replace(/'/g,'&#39;'); }
if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',init); else init();