// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAdventure(arg1) {
  return window['go']['wailsapp']['App']['DeleteAdventure'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['wailsapp']['App']['DeleteSession'](arg1);
}

export function ExportDMBook(arg1, arg2) {
  return window['go']['wailsapp']['App']['ExportDMBook'](arg1, arg2);
}

export function ExportNovel(arg1, arg2) {
  return window['go']['wailsapp']['App']['ExportNovel'](arg1, arg2);
}

export function GetAdventure(arg1) {
  return window['go']['wailsapp']['App']['GetAdventure'](arg1);
}

export function GetConfig() {
  return window['go']['wailsapp']['App']['GetConfig']();
}

export function GetDetail(arg1) {
  return window['go']['wailsapp']['App']['GetDetail'](arg1);
}

export function GetLibrary() {
  return window['go']['wailsapp']['App']['GetLibrary']();
}

export function GetSession() {
  return window['go']['wailsapp']['App']['GetSession']();
}

export function ImportAdventure(arg1) {
  return window['go']['wailsapp']['App']['ImportAdventure'](arg1);
}

export function LoadSession(arg1) {
  return window['go']['wailsapp']['App']['LoadSession'](arg1);
}

export function MarkNPCMet(arg1) {
  return window['go']['wailsapp']['App']['MarkNPCMet'](arg1);
}

export function MoveParty(arg1) {
  return window['go']['wailsapp']['App']['MoveParty'](arg1);
}

export function NewAdventureTemplate() {
  return window['go']['wailsapp']['App']['NewAdventureTemplate']();
}

export function PackageAdventure(arg1, arg2) {
  return window['go']['wailsapp']['App']['PackageAdventure'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['wailsapp']['App']['RenameSession'](arg1, arg2);
}

export function RollTable(arg1) {
  return window['go']['wailsapp']['App']['RollTable'](arg1);
}

export function SaveAdventure(arg1) {
  return window['go']['wailsapp']['App']['SaveAdventure'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['wailsapp']['App']['SaveConfig'](arg1);
}

export function SaveSession() {
  return window['go']['wailsapp']['App']['SaveSession']();
}

export function StartSession(arg1) {
  return window['go']['wailsapp']['App']['StartSession'](arg1);
}

export function Submit(arg1) {
  return window['go']['wailsapp']['App']['Submit'](arg1);
}

export function TriggerEvent(arg1) {
  return window['go']['wailsapp']['App']['TriggerEvent'](arg1);
}
