// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsapp} from '../models';
import {domain} from '../models';

export function DeleteAdventure(arg1:string):Promise<wailsapp.LibraryPayload>;

export function DeleteSession(arg1:string):Promise<wailsapp.LibraryPayload>;

export function ExportDMBook(arg1:string,arg2:boolean):Promise<wailsapp.SubmitResult>;

export function ExportNovel(arg1:string,arg2:boolean):Promise<wailsapp.SubmitResult>;

export function GetAdventure(arg1:string):Promise<domain.Adventure>;

export function GetConfig():Promise<wailsapp.ConfigPayload>;

export function GetDetail(arg1:string):Promise<wailsapp.DetailPayload>;

export function GetLibrary():Promise<wailsapp.LibraryPayload>;

export function GetSession():Promise<wailsapp.SessionPayload>;

export function ImportAdventure(arg1:string):Promise<wailsapp.ActionResult>;

export function LoadSession(arg1:string):Promise<wailsapp.SessionPayload>;

export function MarkNPCMet(arg1:string):Promise<wailsapp.SessionPayload>;

export function MoveParty(arg1:string):Promise<wailsapp.SessionPayload>;

export function NewAdventureTemplate():Promise<domain.Adventure>;

export function PackageAdventure(arg1:string,arg2:string):Promise<wailsapp.SubmitResult>;

export function RenameSession(arg1:string,arg2:string):Promise<wailsapp.LibraryPayload>;

export function RollTable(arg1:string):Promise<wailsapp.SubmitResult>;

export function SaveAdventure(arg1:domain.Adventure):Promise<domain.Adventure>;

export function SaveConfig(arg1:wailsapp.ConfigPayload):Promise<wailsapp.ConfigPayload>;

export function SaveSession():Promise<wailsapp.SubmitResult>;

export function StartSession(arg1:string):Promise<wailsapp.SessionPayload>;

export function Submit(arg1:string):Promise<wailsapp.SubmitResult>;

export function TriggerEvent(arg1:string):Promise<wailsapp.SessionPayload>;
