// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {wailsapp} from '../models';

export function GetAdventure(arg1:string):Promise<domain.Adventure>;

export function GetLibrary():Promise<wailsapp.LibraryPayload>;

export function LoadSession(arg1:string):Promise<wailsapp.SessionPayload>;

export function MoveParty(arg1:string):Promise<wailsapp.SessionPayload>;

export function StartSession(arg1:string):Promise<wailsapp.SessionPayload>;

export function Submit(arg1:string):Promise<wailsapp.SubmitResult>;
